#!/bin/bash
mac=$(uname -s)
if [ $mac == 'Darwin' ]; then
  brew tap awsteiner/science
  brew install o2scl
else
 v=$(apt -qq list libatlas-base-dev 2>/dev/null)
 if [ "$v". == "." ]; then
   sudo apt-get install libatlas-base-dev
 fi
fi
