var p = [
    {"name":"greeting","area":"middle-center", "order":"*"}, 
    {"name":"remote","area":"middle-center", "order":"*"},
    {"name":"soundcloud","area":"middle-center", "order":"*"},
    {"name":"map","area":"middle-center", "order":"*"},
    {"name":"xkcd","area":"middle-center", "order":"*"},
    {"name":"dilbert","area":"middle-center", "order":"*"},
    {"name":"commitstrip","area":"middle-center", "order":"*"},
    {"name":"search","area":"middle-center", "order":"*"},
    {"name":"giphy","area":"middle-center", "order":"*"},
    {"name":"reminder","area":"middle-center", "order":"*"},
    {"name":"timer","area":"middle-center", "order":"*"},
    {"name":"todoist","area":"middle-center", "order":"*"}, 
    {"name":"calendar","area":"top-left", "order":"2"},       
    {"name":"datetime","area":"top-left", "order":"1"},  
    {"name":"weather","area":"top-right", "order":"1"},
    {"name":"traffic","area":"top-right", "order":"2"},
    {"name":"stock","area":"top-right", "order":"3"},
    {"name":"tvshows","area":"top-right", "order":"*"},
    {"name":"ha-display","area":"top-right", "order":"*"},      
    {"name":"commands","area":"bottom-center", "order":"*"},
    {"name":"rss","area":"bottom-center", "order":"*"},   
    {"name":"fitbit","area":"bottom-left", "order":"*"},
    {"name":"scrobbler","area":"bottom-left", "order":"*"}   
]
module.exports= function() { return p};